MCU = STM32F072
BOARD = ST_STM32F072B_DISCOVERY
MCU_LDSCRIPT = STM32F072

DFU_ARGS = -d 0483:df11 -a 0 -s 0x08000000:leave

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
# CUSTOM_MATRIX = lite
RGBLIGHT_ENABLE = no
